Head 
Tail
info
describe
shape 
columns

In [28]:
import pandas as pd 

data = {
    "Name" : ["Mohsin","Ali","Hassan","Toseef"],
    "Score" : [89,99,90,79],
    "Age" : [23,21,24,20],
    "Study_hrs" : [1,2,3,4]
}

df = pd.DataFrame(data)
print(df)

     Name  Score  Age  Study_hrs
0  Mohsin     89   23          1
1     Ali     99   21          2
2  Hassan     90   24          3
3  Toseef     79   20          4

In [ ]:
# i will save this data into csv file

df.to_csv("New_Raw_Data.csv", index= False)

In [6]:
# Head and tail 
# we can show first 5 rows with head and last 5 rows with tail 
# but we can also add number of rows we want to print

df.head(2)

     Name  Score  Age  Study_hrs
0  Mohsin     89   23          1
1     Ali     99   21          2

In [7]:
df.tail(2)

     Name  Score  Age  Study_hrs
2  Hassan     90   24          3
3  Toseef     79   20          4

In [8]:
# Info
# it show all detail about our dataset
# null values , datatype, coulmns..

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       4 non-null      object
 1   Score      4 non-null      int64
 2   Age        4 non-null      int64
 3   Study_hrs  4 non-null      int64
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes

In [9]:
#Describe
#it will show mean , std, max , min .....etc as you are see below

df.describe()

           Score        Age  Study_hrs
count   4.000000   4.000000   4.000000
mean   89.250000  22.000000   2.500000
std     8.180261   1.825742   1.290994
min    79.000000  20.000000   1.000000
25%    86.500000  20.750000   1.750000
50%    89.500000  22.000000   2.500000
75%    92.250000  23.250000   3.250000
max    99.000000  24.000000   4.000000

In [10]:
# if we want to check shape of dataste , how many rows and columns

# we can use shape , it show rows and columns like in output , we have 4, rows and 4 columns in dataset

print(df.shape)

(4, 4)

In [11]:
# if we want to show specific columns from dataset 


df = pd.read_csv("New_Raw_Data.csv")

name = df["Name"]
print(name)

0    Mohsin
1       Ali
2    Hassan
3    Toseef
Name: Name, dtype: object

In [12]:
# two columns 

name = df[["Age","Score"]]
print(name)

   Age  Score
0   23     89
1   21     99
2   24     90
3   20     79

In [13]:
high_salry = df[df['Age']>21]
print(high_salry)

     Name  Score  Age  Study_hrs
0  Mohsin     89   23          1
2  Hassan     90   24          3

In [14]:
filter = df[(df['Age']<23) & (df['Score']>89)]
print(filter)

  Name  Score  Age  Study_hrs
1  Ali     99   21          2

In [15]:
filter = df[(df['Age']>21) | (df['Score']<89)]
print(filter)

     Name  Score  Age  Study_hrs
0  Mohsin     89   23          1
2  Hassan     90   24          3
3  Toseef     79   20          4

Add new columns

In [16]:
print("Add new column in dataset")
# this is meathod, if we don't want to add any value , so just pass
df["Bonus"] = "pass"
# seocnd method , when we want to add value
df['Bonus'] = df['Score']*0.1

print(df)

Add new column in dataset
     Name  Score  Age  Study_hrs  Bonus
0  Mohsin     89   23          1    8.9
1     Ali     99   21          2    9.9
2  Hassan     90   24          3    9.0
3  Toseef     79   20          4    7.9

In [17]:
# if we want to add custom value in column
Number = [3,4,5,6]
df["Number"] = Number

print(df)

     Name  Score  Age  Study_hrs  Bonus  Number
0  Mohsin     89   23          1    8.9       3
1     Ali     99   21          2    9.9       4
2  Hassan     90   24          3    9.0       5
3  Toseef     79   20          4    7.9       6

In [18]:
# we can add in specific column like in code below
# like we can see in output

df.insert(0,"ID",[1,2,3,4])
print(df)

   ID    Name  Score  Age  Study_hrs  Bonus  Number
0   1  Mohsin     89   23          1    8.9       3
1   2     Ali     99   21          2    9.9       4
2   3  Hassan     90   24          3    9.0       5
3   4  Toseef     79   20          4    7.9       6

Remove the column

In [19]:
# This is how we can remove the column
df.drop(columns=['ID'],inplace= True)
print(df)

     Name  Score  Age  Study_hrs  Bonus  Number
0  Mohsin     89   23          1    8.9       3
1     Ali     99   21          2    9.9       4
2  Hassan     90   24          3    9.0       5
3  Toseef     79   20          4    7.9       6

Handling missing Values

In [20]:
# NaN (not a number)
# None
# isnull()
# True = value is missing
# False = value is present



# we will make a new dataset for check missing values

In [21]:
import pandas as pd
import numpy as np
data={
    "Name":['Mohi',"wICKI",'Ali','Zebi','Viki','Joni','Ahmed'],
    "Age":[23,None,21,27,26,31,25],
    "Salary":[50000,None,70000,80000,450000,55000,75000],
    "Performance":[85,None,79,89,91,93,81]
}

df = pd.DataFrame(data)
print(df)

print(df.isnull())

    Name   Age    Salary  Performance
0   Mohi  23.0   50000.0         85.0
1  wICKI   NaN       NaN          NaN
2    Ali  21.0   70000.0         79.0
3   Zebi  27.0   80000.0         89.0
4   Viki  26.0  450000.0         91.0
5   Joni  31.0   55000.0         93.0
6  Ahmed  25.0   75000.0         81.0
    Name    Age  Salary  Performance
0  False  False   False        False
1  False   True    True         True
2  False  False   False        False
3  False  False   False        False
4  False  False   False        False
5  False  False   False        False
6  False  False   False        False

Dropna(): if any row have even one nan value , the full row will be remove

In [22]:
# if we want to remove missing values from dataset 

''' we have major difference see here , when i don't put inplace = True , it
give copy of dataset . it does't change into original datset
, as you see we have one emlement is more in name "wICKI"  so when run
the code 1 rows become more and other vlaues are NaN,'''

''' if we put inplace = True then the wICKI element will be reomve from datset 
because inplace = True means it change original datset 
'''
''' also the concept of dropna is that if a NaN value exist in a row then the 
full row will be remove'''

df.dropna()
print(df)

    Name   Age    Salary  Performance
0   Mohi  23.0   50000.0         85.0
1  wICKI   NaN       NaN          NaN
2    Ali  21.0   70000.0         79.0
3   Zebi  27.0   80000.0         89.0
4   Viki  26.0  450000.0         91.0
5   Joni  31.0   55000.0         93.0
6  Ahmed  25.0   75000.0         81.0

In [23]:
df.dropna(inplace=True)
print(df)

    Name   Age    Salary  Performance
0   Mohi  23.0   50000.0         85.0
2    Ali  21.0   70000.0         79.0
3   Zebi  27.0   80000.0         89.0
4   Viki  26.0  450000.0         91.0
5   Joni  31.0   55000.0         93.0
6  Ahmed  25.0   75000.0         81.0

In [24]:
# if we want to remove specific value from dataset 
# and also can add value in dataset

import pandas as pd
import numpy as np


data= {
    "Name": ["Mohsin ","Ali","Roshni","Mohi","Shamme","Bablu"],
    "Age":[21,None,23,24,18,20],
    "Salary":[20000,30000,None,60000,70000,80000]
}
df = pd.DataFrame(data)
print(df)

remove = df.at[1,"Age"] = 90
print(df)

      Name   Age   Salary
0  Mohsin   21.0  20000.0
1      Ali   NaN  30000.0
2   Roshni  23.0      NaN
3     Mohi  24.0  60000.0
4   Shamme  18.0  70000.0
5    Bablu  20.0  80000.0
      Name   Age   Salary
0  Mohsin   21.0  20000.0
1      Ali  90.0  30000.0
2   Roshni  23.0      NaN
3     Mohi  24.0  60000.0
4   Shamme  18.0  70000.0
5    Bablu  20.0  80000.0

In [25]:
# add value with fillna like below in code
import pandas as pd


data= {
    "Name": [None,"Ali","Roshni","Mohi","Shamme","Bablu"],
    "Age":[21,None,23,24,18,20],
    "Salary":[20000,30000,None,60000,70000,80000]
}
df = pd.DataFrame(data)

df.fillna(0, inplace=True)
print(df)

     Name   Age   Salary
0       0  21.0  20000.0
1     Ali   0.0  30000.0
2  Roshni  23.0      0.0
3    Mohi  24.0  60000.0
4  Shamme  18.0  70000.0
5   Bablu  20.0  80000.0

In [26]:
import pandas as pd


data= {
    "Name": [None,"Ali","Roshni","Mohi","Shamme","Bablu"],
    "Age":[21,None,23,24,18,20],
    "Salary":[20000,30000,None,60000,70000,80000]
}
df = pd.DataFrame(data)

df["Age"].fillna(df["Age"].mean(), inplace=True)
df['Salary'].fillna(df["Salary"].mean(), inplace=True)
print(df)

     Name   Age   Salary
0    None  21.0  20000.0
1     Ali  21.2  30000.0
2  Roshni  23.0  52000.0
3    Mohi  24.0  60000.0
4  Shamme  18.0  70000.0
5   Bablu  20.0  80000.0

C:\Users\hp\AppData\Local\Temp\ipykernel_11448\4059763953.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
C:\Users\hp\AppData\Local\Temp\ipykernel_11448\4059763953.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df["Salary"].mean(), inplace=True)

In [27]:
print(df)

     Name   Age   Salary
0    None  21.0  20000.0
1     Ali  21.2  30000.0
2  Roshni  23.0  52000.0
3    Mohi  24.0  60000.0
4  Shamme  18.0  70000.0
5   Bablu  20.0  80000.0